### ISSUE TITLE
Move to Yggdrasil

### ISSUE THREAD

**Issue by staticfloat** [bicycle1885/ZlibBuilder#15]
Hey Kenta,

Just letting you know that I have [copied this build recipe over into Yggdrasil](https://github.com/JuliaPackaging/Yggdrasil/commit/1d22c3e4e2ced867166e870f126c0ffba203f80a) and built it with my WIP BB branch, which means that it autogenerated a [Julia wrapper package]((https://github.com/JuliaBinaryWrappers/Zlib_jll.jl) (we call these "JLL packages") which is a normal, registered package that has an [Artifacts.toml](https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/blob/11a3d36df1340892e73ce3cd209c7298f04dc603/Artifacts.toml) file embedded within it.

This means that, on Julia 1.3+, you can now use zlib in a much more convenient way; in your packages such as `CodecZlib`, instead of including a `build.jl` file and requiring users to do a `Pkg.build()`, you just list `Zlib_jll` as a dependent package.  You can then do things like:

```julia
# Zlib_jll exports the `libz` symbol, because it is listed as a `Product` in the `build_tarballs.jl` file
using Zlib_jll

# `libz` is now a string with the proper SONAME of `libz` already dlopen'ed; so you can use it in `ccall()` directly.
unsafe_string(ccall((:zlibVersion, libz), Ptr{UInt8}, ()))
```

I'm letting you know this for two reasons; first, so that you can enjoy the fruits of our work over the past many months in trying to build a better binary deployment strategy for your packages, and also to let you know that I did the work of copying this repository over into Yggdrasil for you, so you don't need to do it.

**Comment by staticfloat** [comment]
@bicycle1885 I realized I didn't ping you, and if you're anything like me, you definitely will never see this unless you're explicitly pinged.  :)

**Comment by bicycle1885** [comment]
Thank you for your notice! Yeah, I wouldn't have noticed if you hadn't pinged me.

Let me ask a question. Do I need to maintain this repository for Julia 1.0, 1.1, and 1.2? My understanding is that Artifacts will be introduced from Julia 1.3 and thus the older Julias cannot use them. Or, can [these released artifacts](https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases) of Zlib_jl.jl still be used for Julia 1.0-1.2 as drop-in replacements of binary artifacts released here?

**Comment by staticfloat** [comment]
They can still be used; but since there is no `build.jl` that is being auto-generated, if you need to update which binaries are being downloaded in your `build.jl`, you'll just need to edit the URLs and git sha's manually.  If you need to do that, feel free to ping me, there's a function called [`product_hashes_from_github_release()`](https://github.com/JuliaPackaging/BinaryBuilder.jl/blob/391b7ea764b6f0be1b1d3f7df289ede08ec55251/src/AutoBuild.jl#L661-L713) that can help with it so that it's not so tedious.

**Comment by bicycle1885** [comment]
Thank you! I'm going to keep this repository for a while to distribute binary artifacts for Julia 1.0-1.2 since zlib is very stable and thus we don't need to update it very often.
